---
Name: idlelock
---

# Add a field to Group to configure the lockout threshold
SilverStripe\Security\Group:
  extensions:
    - DNADesign\IdleLock\Extensions\GroupLockoutThresholdExtension

SilverStripe\Security\Member:
  lockout_threshold_days: 30 # Default lockout threshold
  extensions:
    - DNADesign\IdleLock\Extensions\MemberLockoutExtension
