---
Name: idlelock
---

# Add a field to Group to configure the lockout time
SilverStripe\Security\Group:
  extensions:
    - DNADesign\IdleLock\Extensions\GroupLockoutThresholdExtension
SilverStripe\Security\Member:
  lockout_threshold: 30 # Default lockout period
  extensions:
    - DNADesign\IdleLock\Extensions\MemberLockoutExtension
