---
Name: idlelock
---

SilverStripe\Security\Member:
  lockout_threshold_days: 30
  lockout_message: 'This account has been locked. Please contact an administrator.'
  extensions:
    - DNADesign\IdleLock\Extensions\MemberLockoutExtension

SilverStripe\Security\Group:
  extensions:
    - DNADesign\IdleLock\Extensions\GroupLockoutExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - DNADesign\IdleLock\Extensions\SiteConfigLockoutExtension
